[versions]
agp = "8.13.1"
googleApiClientAndroid = "2.8.1"
googleApiServicesDrive = "v3-rev20230815-2.0.0"
googleAuthLibraryOauth2Http = "1.40.0"
googleHttpClientGson = "2.0.2"
guava = "33.5.0-android"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
googleid = "1.1.1"
okhttp = "5.3.2"
playServicesAuth = "21.4.0"
googleGmsGoogleServices = "4.4.4"
firebaseFirestoreVersion = "26.0.2"
firebaseStorage = "22.0.1"

[libraries]
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroid" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDrive" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuthLibraryOauth2Http" }
google-http-client-android = { module = "com.google.http-client:google-http-client-android", version.ref = "googleHttpClientGson" }
google-http-client-gson = { module = "com.google.http-client:google-http-client-gson", version.ref = "googleHttpClientGson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-camera-core = { module = "androidx.camera:camera-core", version = "1.3.4" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version = "1.3.4" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version = "1.3.4" }
androidx-camera-video = { module = "androidx.camera:camera-video", version = "1.3.4" }
androidx-camera-view = { module = "androidx.camera:camera-view", version = "1.3.4" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
tutorial-android = { group = "com.github.TutorialsAndroid", name = "GButton", version = "1.0.19" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
gms-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestoreVersion" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

